### PR TITLE
Modify controller to support TorchScript and ONNX

### PR DESCRIPTION
**Pull request by Mika412**
I modified the code to support TorchScript. This has around 70% improvement during inference. Don't know the performance for training though. 

There is also a way to only compile the Model, Cost, and Update models instead of the whole Controller, which then allows to have TensorBoard logging. This drops the performance boost to around 60%.

### CODE REVIEW

**Review by NicolayP — CHANGES_REQUESTED** [review]
It looks like in mppi_base line 137 you set the type to torch.double and not dtype.

**Comment by Mika412** [comment]
Yes, it's because for some reason it doesn't allow me to use dtype there. I probably could find a different approach to that

**Comment by Mika412** [comment]
So I've checked the ONNX, and it seems that it's having way better performance than before. Maybe it's due to the TorchScript changes.  
I had to reduce the samples and tau, as it was taking a bit too long for a quick test.

image

**Review by NicolayP — APPROVED** [review]

**Comment by NicolayP** [comment]
So I double checked with ONNX but this time setting the parameters to be 2k samples and 50 steps and I get this super impressive speedup that sounds too good to be true to me and Ignacio haha. 

Screenshot from 2023-07-10 11-38-02

In subsequent runs I got up to 786x speedup 

What do you think? Does this make sens?
I'll try to double check that it produces the expected results

**Comment by Mika412** [comment]
Damn, this seems very weird. It may be optimizing it too much, or maybe the model is just very compressible. I'll check it in a bit on my side. Another thing that I noticed, is that for some reason it runs faster on the CPU than the GPU.

After lunch, I'll also do a C++ PR. Based on that, we can check if it's a fluke

**Comment by NicolayP** [comment]
Okay I noticed that I was running the model compiled on k=20 h=5, that is probably the "problem" 
Is there a moment (k high) where it becomes faster on GPU than CPU?

**Comment by NicolayP** [comment]
How long does the compilation to onnx usually take? I'ts been going on for almost 1h30. Could it be in a soft lock without any warning?

**Comment by Mika412** [comment]
Well, I haven't tried any larger sample/steps. But I'm currently running with 2000 steps, and it's been an hour. I don't think it's soft-locked, as it's increasing the VRAM usage. Although, very slowly.

**Pull request merged**
